### PR TITLE
Fix quoted comments

### LINKED ISSUE #369: Paths for quoted keys don't filter correctly
I had some cases where comments from a comment map didn't show up in the marshaled yaml, and I realized these cases all have keys that require quotes.

Here's a test demonstrating this:
https://go.dev/play/p/U7B7jbXcKg4

I traced it down to path filter not matching in these cases. There is a PR incoming.

### PR DESCRIPTION
**Pull request by WillAbides**
fixes #369 

This resolves the quoted comments issue by updating the path filter account for quoted selectors.

Slightly related to this, I found that `Path.String()` wasn't normalizing its output. I had to remove the `*PathBuilder` receiver from `normalizeSelectorName()` to make this work.

The changes to `context.go` are not related to the rest of this PR. While tracing this I noticed that `context.mode` isn't used, so I removed it.

### CODE REVIEW

File: path.go [hunk 1]
```diff
@@ -387,26 +387,12 @@ func (b *PathBuilder) Recursive(selector string) *PathBuilder {
...
-	return false
-}
-
-func (b *PathBuilder) enclosedSingleQuote(name string) bool {
-	return strings.HasPrefix(name, "'") && strings.HasSuffix(name, "'")
-}
-
-func (b *PathBuilder) normalizeSelectorName(name string) string {
-	if b.enclosedSingleQuote(name) {
+func normalizeSelectorName(name string) string {
```
Comment (goccy) [inline path.go:390]: Can it be modified to minimize the difference ?
If necessary, I would like to do the refactoring separately.

**Review by goccy — CHANGES_REQUESTED** [review]
Thank you for your contribution ! I've commented.

File: path.go (hunk 1 above)
Comment (WillAbides) [reply path.go]: Updated

File: path.go [hunk 2]
```diff
@@ -500,11 +500,27 @@ func newSelectorNode(selector string) *selectorNode {
 }
 
 func (n *selectorNode) filter(node ast.Node) (ast.Node, error) {
+	selector := n.selector
+	if len(selector) > 0 && selector[0] == '\'' {
+		selector = selector[1 : len(selector)-1]
```
Comment (goccy) [inline path.go:505]: Is there any need to check that single quote is not used as the terminating character as in `'selector` ?

File: path.go [hunk 3]
```diff
@@ -500,11 +500,27 @@ func newSelectorNode(selector string) *selectorNode {
...
+			if len(key) > 0 {
+				switch key[0] {
+				case '"':
+					var err error
+					key, err = strconv.Unquote(key)
+					if err != nil {
+						return nil, errors.Wrapf(err, "failed to unquote")
+					}
+				case '\'':
+					key = key[1 : len(key)-1]
```
Comment (goccy) [inline path.go:520]: It seems that this one also require validation of the terminating character as well.

**Comment by goccy** [comment]
@WillAbides Sorry for the long wait, I made a couple of comments.

**Review by goccy — APPROVED** [review]
Thank you for your contribution ! LGTM 👍
